# Generated by Django 5.0 on 2024-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=6),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6),
        ),
    ]
