# Generated by Django 5.0 on 2024-03-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodtest', '0002_alter_bloodtest_blood_group_alter_bloodtest_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
    ]
