# Generated by Django 5.0 on 2024-03-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blooddonation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodDonor',
            new_name='BloodDonation',
        ),
    ]
