# Generated by Django 5.0 on 2024-03-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blooddonation', '0002_rename_blooddonor_blooddonation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonation',
            old_name='date_of_birth',
            new_name='date_of_donation',
        ),
    ]
