# Generated by Django 5.0 on 2024-03-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slotbooking',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_mobile', models.IntegerField(unique=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('patient_gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=1)),
            ],
        ),
    ]
