# Generated by Django 5.0 on 2024-03-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='patient_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='booking_time',
            field=models.CharField(max_length=20),
        ),
    ]
