# Generated by Django 5.0 on 2024-03-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0002_slotbooking_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='patient_mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
