# Generated by Django 5.0 on 2024-03-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0004_alter_slotbooking_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='patient_mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
