# Generated by Django 5.0 on 2024-03-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0005_alter_slotbooking_patient_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
