# Generated by Django 5.0 on 2024-03-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0006_alter_slotbooking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbooking',
            name='booking_date',
        ),
    ]
