# Generated by Django 5.0 on 2024-03-27 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0007_remove_slotbooking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
