# Generated by Django 5.0 on 2024-03-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0008_slotbooking_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotbooking',
            old_name='booking_date',
            new_name='booking',
        ),
    ]
